### ISSUE TITLE
Certificate's CN

### ISSUE THREAD

**Issue by atifwaqar** [programistka/WebSocketsDemo#1]
Hi,

I am using this demo application to connect to a websocket server. but when i connect i get an exception : 
"System.Exception: RemoteCertificateChainErrors
System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure"

i have searched on google and found many threads for this error. all are pointing the error at Certificate's CN(Common Name).

Can you please help me in modifying my Certificate's CN?

Thank you !

**Comment by magoswiat** [comment]
Have you tried solution provided for similar problem here: http://websocket4net.codeplex.com/discussions/403908 ?

**Comment by atifwaqar** [comment]
Thank you very much for your response. i have tried this solution. i am
stuck at another part now. when start a connection to the server i get an
exception of "handshake Response is invalid". Do you have any clue what can
be the issue here?

Best Regards,
Atif Waqar

**Comment by magoswiat** [comment]
I would check headers sent between server and client. Maybe there is missing any and that is why handshake isn't succeeded.

**Comment by atifwaqar** [comment]
You are correct. the headers were the issue. thank you very very much. i
was stuck in this for like a week.

Thanks again :)

Best Regards,
Atif Waqar

**Comment by magoswiat** [comment]
Nice to hear that, so good luck and have fun! Regards!

**Comment by atifwaqar** [comment]
Thanks. and have a great year ahead :)

Best Regards,
Atif Waqar
